version: '3.8'

volumes:
  pg-data:

networks:
  gateway: {}


services:
  db:
    container_name: postgres14
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - gateway
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
